# Generated by Django 5.2.4 on 2025-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('statut', models.CharField(default='en_attente', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur_id', models.IntegerField(default=1)),
            ],
        ),
    ]
