# Generated by Django 5.2.4 on 2025-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='sla',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='statut',
            field=models.CharField(default='en attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='utilisateur_id',
            field=models.IntegerField(),
        ),
    ]
